name = "greenoil-api"
main = "index.js"
compatibility_date = "2024-09-01"

[vars]
WORKER_USERNAME = "greenoil"
WORKER_PASSWORD = "greenoil2025"

# Note: Set your GOOGLE_MAPS_API_KEY as a Cloudflare Secret:
# wrangler secret put GOOGLE_MAPS_API_KEY
